# golangci-lint configuration for nifiparser
# Reference: https://golangci-lint.run/usage/configuration/

run:
  # Timeout for analysis
  timeout: 5m
  
  # Go version to target
  go: "1.21"

# Output configuration options
output:
  # Colored output
  formats:
    - format: colored-line-number
  
  # Print lines of code with issue
  print-issued-lines: true
  
  # Print linter name in issue line
  print-linter-name: true

# All available linters
linters:
  disable-all: true
  enable:
    # Default linters
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Official Go tool for examining Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Go static analysis
    - typecheck     # Type checking
    - unused        # Check for unused constants, variables, functions

    # Additional recommended linters
    - gofmt         # Check code formatting
    - goimports     # Check import formatting
    - misspell      # Find commonly misspelled words
    - revive        # Fast, configurable, extensible linter
    - gosec         # Security-focused linter
    - gocritic      # Opinionated linter
    - bodyclose     # Check HTTP response body is closed
    - dupl          # Code clone detection
    - gocyclo       # Cyclomatic complexity
    - goprintffuncname # Check printf-like function names
    - nakedret      # Finds naked returns
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Unused function parameters
    - whitespace    # Whitespace issues

# Linter-specific settings
linters-settings:
  errcheck:
    # Report assignments of errors to blank identifier
    check-blank: true
    # Report type assertions like a := b.(MyStruct)
    check-type-assertions: true

  govet:
    # Enable all analyzers
    enable-all: true
    # Disable specific analyzers
    disable:
      - fieldalignment  # Too strict for this project

  gocyclo:
    # Minimal cyclomatic complexity to report
    min-complexity: 15

  dupl:
    # Minimum token threshold for duplication detection
    threshold: 100

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - hugeParam
      - rangeValCopy

  revive:
    rules:
      - name: cognitive-complexity
        arguments: [15]
      - name: cyclomatic
        arguments: [15]

  misspell:
    locale: US

  nakedret:
    # Maximum function lines for naked returns
    max-func-lines: 0  # Disallow all naked returns

  gosec:
    # Exclude specific rules (optional)
    excludes:
      - G104  # Allow unhandled errors in certain contexts

# Issues configuration
issues:
  # Which dirs to exclude: issues from them won't be reported
  exclude-dirs:
    - vendor
    - testdata
  
  # Which files to exclude: they won't be analyzed
  exclude-files:
    - ".*\\.pb\\.go$"
  
  # Maximum issues count per linter
  max-issues-per-linter: 0
  
  # Maximum count of issues with same text
  max-same-issues: 0
  
  # Exclude some linters from running on tests files
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - gocyclo
        - errcheck

    # Exclude test files from certain checks
    - path: _test\.go
      text: "G404:"  # Weak random number generator is OK in tests

  # Independently of option `exclude` golangci-lint uses default exclude patterns
  exclude-use-default: false
